### ISSUE TITLE
Cannot find module 'bignumber.js' or its corresponding type declarations.

### ISSUE THREAD

**Issue by everhardt** [hildjj/node-cbor#140]
I get the following errors when compiling my TypeScript code that includes the cbor package:

```
node_modules/cbor/types/lib/cbor.d.ts:1:37 - error TS2307: Cannot find module 'bignumber.js' or its corresponding type declarations.

1 export var BigNumber: typeof import("bignumber.js").default;
                                      ~~~~~~~~~~~~~~

node_modules/cbor/types/lib/constants.d.ts:78:27 - error TS2307: Cannot find module 'bignumber.js' or its corresponding type declarations.

78 import { BigNumber } from "bignumber.js";
                             ~~~~~~~~~~~~~~
```

Could the problem be that bignumber.js is now not installed by default, while is still referred to in the two TypeScript declaration files above? If I add bignumer.js to my package, all is well again..

**Comment by hildjj** [comment]
Yes, that's probably it.  Making bignumber.js optional has been pretty complicated.  If your protocol isn't using big decimals or big floats, I can understand why you wouldn't want to take a bignumber.js dependency.  I *think* you should be able to use it as a devDependency for now, but I'll see if I can figure out some way around this.

Since I'm not a TypeScript person, I'm open to suggestions.  The only thing that comes to mind at the moment is to completely remove bignumber.js, turn the cbor integration for it into another parallel package, and rev the major version number -- but that's a pretty big change.

**Comment by everhardt** [comment]
> The only thing that comes to mind at the moment is to completely remove bignumber.js, turn the cbor integration for it into another parallel package, and rev the major version number -- but that's a pretty big change.

Yeah, that or just providing example code on how to add them yourself as a new Encoder and Decoder. But in any case it would be breaking.

**Comment by hildjj** [comment]
Please retest with v8.0.0 and reopen if this isn't fixed.

**Comment by everhardt** [comment]
Works like a charm!
