### ISSUE TITLE
ndjson

### ISSUE THREAD

**Issue by jbenet** [hildjj/node-cbor#19]
might be nice to have an `-n` option on the `cbor2json` and `json2cbor` tools to use streaming (with ndjson). See https://github.com/jbenet/node-ubjson-stream#streaming

**Comment by hildjj** [comment]
Can you say a little more about how you want those tools to act differently with -n?  I'm assuming:

- Don't stop reading after the first full object is read
- still shut down on stdin EOF

This should be pretty easy for cbor2json, but I'd rather not take another dependency in order to get streaming JSON input in json2cbor.

**Comment by hildjj** [comment]
Oh, also, I'm a little more interested in RFC 7464 (https://tools.ietf.org/html/rfc7464) as the JSON input.

**Comment by jbenet** [comment]
> - Don't stop reading after the first full object is read
> - still shut down on stdin EOF

Right. 

> I'd rather not take another dependency in order to get streaming JSON input in json2cbor.
I think https://github.com/maxogden/ndjson is not that bad of a dep. 

https://github.com/jbenet/node-cbor/pull/1 is a possible example.

**Comment by hildjj** [comment]
Fixed in #22
